#################################################
# DO Community Playbooks: Docker
#################################################
# most from https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-cluster-using-kubeadm-on-ubuntu-18-04
# To install it use: ansible-galaxy collection install community.general

---

- hosts: group
  become: true
  #  vars_files:
  # - vars/default.yml
  vars:
    password: F@lcon12
    key: "key"


  tasks:

     ##################################
     #  Add User
     #################################

    - name: Add user traveler with a password
      user:
        name: traveler
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create

    - name: allow 'traveler' to have passwordless sudo
      lineinfile:
              dest: /etc/sudoers
              line: 'traveler ALL=(ALL) NOPASSWD: ALL'
              validate: 'visudo -cf %s'

    - name: Set up multiple authorized keys
      authorized_key:
        user: traveler
        state: present
        key: '{{ item }}'
      with_file:
        - traveler-genie.key
        - traveler-kvm-00.key
        - traveler-surface.key
        - traveler-docker2.key
    


   
